################################################################################
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

name: Bug report ðŸž
description: Problems, bugs and issues with Fluss
type: "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thank you very much for your feedback!
  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search [issues](https://github.com/alibaba/fluss/issues) to check if your issue has already been reported.
      options:
        - label: >
            I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.
          required: true
  - type: dropdown
    attributes:
      label: Fluss version
      description: What Fluss version are you using?
      multiple: false
      options:
        - "0.7.0 (latest release)"
        - "0.6.0"
        - "0.5.0"
        - "main (development)"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Please describe the bug ðŸž
      description: >
        Please describe the problem, what to expect, and how to reproduce.
        Feel free to include stacktraces and the Fluss server/client configuration.
        You can include files by dragging and dropping them here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solution
      description: Describe the proposed solution about how to fix it if any.
  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        We look forward to the community of developers or users helping solve Fluss problems together. If you are willing to submit a PR to fix this problem, please check the box.
      options:
        - label: I'm willing to submit a PR!
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
